name: Build and deploy Node.js app to Azure Web App - Coworkbackend
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip release.zip ./* -r
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DBF26DE9AD944A181385937D177730D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE6E19810F8A45D0BE31FDF7FC019DF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08A62E7788A142DDA66CC179F2E3A723 }}
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Coworkbackend'
          slot-name: 'Production'
          package: .
